# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_home": "00_core.ipynb",
         "L_ROOT": "00_core.ipynb",
         "D_ROOT": "00_core.ipynb",
         "DBS": "00_core.ipynb",
         "IMG_SIZE_LG": "00_core.ipynb",
         "IMG_SIZE_MD": "01_data.ipynb",
         "IMG_SIZE_SM": "00_core.ipynb",
         "IMG_SIZE": "01_data.ipynb",
         "IMG_SIZES": "00_core.ipynb",
         "ABBR": "00_core.ipynb",
         "ZAPPOS_DF_SIMPLIFIED": "01_data.ipynb",
         "ZAPPOS_FEATS_ALL": "01_data.ipynb",
         "ZAPPOS_FEATS_ALL_SORT": "01_data.ipynb",
         "ZAPPOS_FEATS_SM": "00_core.ipynb",
         "ZAPPOS_FEATS_MD": "01_data.ipynb",
         "ZAPPOS_FEATS_LG": "00_core.ipynb",
         "get_zappos_db": "01_data.ipynb",
         "DB_PATH": "01_data.ipynb",
         "read_zappos_meta": "01_data.ipynb",
         "simplify_zappos_db": "01_data.ipynb",
         "skl_tt_split": "01_data.ipynb",
         "creat_full_local_categorydirs": "01_data.ipynb",
         "create_test_train_directories": "01_data.ipynb",
         "get_cuda": "02a_model.ipynb",
         "get_cpu": "02a_model.ipynb",
         "get_mnetV2_feature_net": "02a_model.ipynb",
         "mnetv2": "02a_model.ipynb",
         "get_feats_dls": "02a_model.ipynb",
         "get_all_feats0": "02a_model.ipynb",
         "get_all_feats": "02a_model.ipynb",
         "save_featsXsize": "02a_model.ipynb",
         "collate_featsXsize": "02a_model.ipynb",
         "load_and_prep_sneaker": "02a_model.ipynb",
         "get_mnet_feature": "02a_model.ipynb",
         "get_umap_reducer": "03_model.ipynb",
         "query_neighs": "03_model.ipynb",
         "plot_sneak_neighs": "03_model.ipynb",
         "get_umap_embedding": "03_model.ipynb",
         "on_click_find_similar": "03_model.ipynb",
         "btn_run": "03_model.ipynb",
         "out_pl": "03_model.ipynb",
         "lbl_neighs": "03_model.ipynb",
         "btn_upload": "03_model.ipynb"}

modules = ["core.py",
           "data.py",
           "model.py"]

doc_url = "https://ergonyc.github.io/snkr-finder/"

git_url = "https://github.com/ergonyc/snkr-finder/tree/master"

def custom_doc_links(name): return None
