# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['get_home', 'L_ROOT', 'D_ROOT', 'DBS', 'IMG_SIZE_LG', 'IMG_SIZE_MD', 'IMG_SIZE_SM', 'IMG_SIZE', 'IMG_SIZES',
           'ABBR', 'ZAPPOS_DF_SIMPLIFIED', 'ZAPPOS_FEATS_ALL', 'ZAPPOS_FEATS_ALL_SORT', 'ZAPPOS_FEATS_SM',
           'ZAPPOS_FEATS_MD', 'ZAPPOS_FEATS_LG']

# Cell
from .imports import *


# Cell
def get_home():
    return Path().home()


# Cell

L_ROOT = get_home()/'Projects/Project2.0/snkr-finder'
D_ROOT = get_home()/'Projects/DATABASE'


DBS = {"zappos": "ut-zap50k-images",
      "sns": "scraped/sns/im",
      "goat": "scraped/goat/im"}

IMG_SIZE_LG = 224
IMG_SIZE_MD = 160
IMG_SIZE_SM = 128
IMG_SIZE = IMG_SIZE_MD

IMG_SIZES = {"small":  IMG_SIZE_SM,
             "medium": IMG_SIZE_MD,
             "large":  IMG_SIZE_LG}

ABBR = {"small": "sm", "medium": "md", "large":"lg"}

ZAPPOS_DF_SIMPLIFIED = "zappos-50k-simplified_sort"

ZAPPOS_FEATS_ALL = "zappos-50k-mobilenetv2-features_"
ZAPPOS_FEATS_ALL_SORT = "zappos-50k-mobilenetv2-features_sort_3"

ZAPPOS_FEATS_SM = f"mobilenetv2-features_small"
ZAPPOS_FEATS_MD = f"mobilenetv2-features_medium"
ZAPPOS_FEATS_LG = f"mobilenetv2-features_large"

